apiVersion: v1
kind: Secret
metadata:
  name: {{ include "candidate-bot.fullname" . }}-secrets
  labels:
    {{- include "candidate-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN_CANDIDATE: {{ .Values.secrets.telegramBotToken | quote }}
  WEBHOOK_SECRET_CANDIDATE: {{ .Values.secrets.webhookSecret | quote }} 