apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hm-bot.fullname" . }}-secrets
  labels:
    {{- include "hm-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
