apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "candidate-landing.fullname" . }}
  labels:
    {{- include "candidate-landing.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "candidate-landing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "candidate-landing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: candidate-landing
          image: {{ include "candidate-landing.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: TELEGRAM_BOT_URL
              value: {{ .Values.config.telegramBotUrl | quote }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

