apiVersion: v1
kind: Service
metadata:
  name: {{ include "candidate-landing.fullname" . }}
  labels:
    {{- include "candidate-landing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "candidate-landing.selectorLabels" . | nindent 4 }}

