apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-api.fullname" . }}-secrets
  labels:
    {{- include "core-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}

