apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-api.fullname" . }}
  labels:
    {{- include "core-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
  selector:
    {{- include "core-api.selectorLabels" . | nindent 4 }}
